In [45]:
# data normalisation with sklearn
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats


In [46]:
white_wine = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv', sep=";")

In [47]:
ohe = OneHotEncoder

In [48]:
white_wine['quality_label'] = white_wine['quality'].apply(lambda value: 'low'
if value <= 4 else 'medium'
if value <= 6 else 'high')

# 3 4 5 are low, 6 7 medium, 8 and nonexistent 9 are high
#changed to: 3 4 low, 5 6 medium, 7 8 (and 9) high

white_wine['quality_label'] = pd.Categorical(white_wine['quality_label'],
categories=['low', 'medium', 'high'])

white_wine.head(5)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality quality_label  
0      8.8        6        medium  
1      9.5        6        medium  
2     10.1        6        medium  
3      9.9        6        medium  
4      9.9        6        medium

In [49]:
#Skewness measures asymmetry in the data distribution

#print(white_wine['residual sugar'].astype(float).skew())

In [50]:
#Kurtosis identifies outliers: data with high kurtosis (heavy-tailed data) is proof of outliers, and data with low kurtosis (light-tailed data) lacks them.

#print(white_wine['residual sugar'].astype(float).kurt())

In [51]:
# x is all the features Im keeping
# y is target, quality , the new name.

#X.drop(['SalePrice'],axis=1,inplace=True) REMEMBER THE INPLACE!!

In [52]:
#white_wine["quality_label"].unique()
#white_wine ["quality_label"].value_counts()

In [53]:
le = LabelEncoder()

In [54]:
new_wine = pd.DataFrame(white_wine, columns=['quality_label'])

new_wine['quality_label'] = new_wine['quality_label'].astype('category')

new_wine['quality_label_Cat'] = new_wine['quality_label'].cat.codes

new_wine.head(5)

quality_label  quality_label_Cat
0        medium                  1
1        medium                  1
2        medium                  1
3        medium                  1
4        medium                  1

In [55]:
x_data = white_wine[["fixed acidity", "volatile acidity", "citric acid", "residual sugar", "chlorides", "free sulfur dioxide", "total sulfur dioxide", "density", "pH", "sulphates", "alcohol"]]
y_data = new_wine["quality_label_Cat"]


In [56]:
new_frame = [white_wine, new_wine]
new_frame


[      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
 0               7.0              0.27         0.36            20.7      0.045   
 1               6.3              0.30         0.34             1.6      0.049   
 2               8.1              0.28         0.40             6.9      0.050   
 3               7.2              0.23         0.32             8.5      0.058   
 4               7.2              0.23         0.32             8.5      0.058   
 ...             ...               ...          ...             ...        ...   
 4893            6.2              0.21         0.29             1.6      0.039   
 4894            6.6              0.32         0.36             8.0      0.047   
 4895            6.5              0.24         0.19             1.2      0.041   
 4896            5.5              0.29         0.30             1.1      0.022   
 4897            6.0              0.21         0.38             0.8      0.020   
 
       free su

In [57]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_data, y_data ,test_size = 0.3, shuffle=False)
x_train, x_test, y_train, y_test

#this is fine!

(      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
 0               7.0              0.27         0.36           20.70      0.045   
 1               6.3              0.30         0.34            1.60      0.049   
 2               8.1              0.28         0.40            6.90      0.050   
 3               7.2              0.23         0.32            8.50      0.058   
 4               7.2              0.23         0.32            8.50      0.058   
 ...             ...               ...          ...             ...        ...   
 3423            7.1              0.18         0.39           14.50      0.051   
 3424            6.4              0.32         0.27            4.90      0.034   
 3425            7.1              0.17         0.40           14.55      0.047   
 3426            7.1              0.17         0.40           14.55      0.047   
 3427            5.8              0.24         0.26           10.05      0.039   
 
       free su

In [58]:
# data normalisation with sklearn
from sklearn.preprocessing import MinMaxScaler

# fit scaler on training data
norm = MinMaxScaler().fit(x_train)

# transform training data
X_train_norm = norm.transform(x_train)

# transform testing data
X_test_norm = norm.transform(x_test)

In [59]:
len(x_test)

1470

In [60]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler


In [61]:
#DECISION TREE
#example: the companies and salaries
#Gini impurity (one little dot bothers the whole picture)

from sklearn import tree



In [62]:
inputs = white_wine.drop("quality_label", axis="columns")
target = white_wine["quality_label"]

In [63]:
model = tree.DecisionTreeClassifier()

In [64]:
white_wine.drop(labels=["quality", "quality_label"], axis="columns", inplace= False)


fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  
0         8.8  
1         9.5  
2        10.1  
3         9.9  
4         9.9  
...       ...  
4893     11.2  
4894      9.6  
4895      9.4  
4896     12.8  
4897     11.8  

[4898 rows x 11 columns]

In [83]:
model.fit(white_wine, target)

ValueError: could not convert string to float: 'medium'

In [66]:
#model.score(inputs, target)

In [67]:
#model.predict([[1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5]])

#array(['high'], dtype=object) this means that a wine with these nrs will be high quality.



In [71]:
clf = tree.DecisionTreeClassifier()

In [72]:

clf.fit(x_train, y_train)

DecisionTreeClassifier()

In [73]:
# Make predictions
clf = clf.predict(x_test)
clf

array([1, 1, 1, ..., 1, 2, 2], dtype=int8)

In [74]:
#DECISION TREE
#example: the companies and salaries
#Gini impurity (one little dot bothers the whole picture)

from sklearn import tree

In [76]:
model = tree.DecisionTreeClassifier()

In [77]:
#white_wine.drop(labels=["quality", "quality_label"], axis="columns", inplace= False)


In [78]:
white_wine.loc[white_wine['quality_label'] == '', 'quality_label'] = 1


white_wine['quality_label']=white_wine['quality_label'].astype(float)

TypeError: Cannot setitem on a Categorical with a new category (1), set the categories first

In [ ]:
model.score(inputs, target)

/Users/monicavillarfuentes/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names seen at fit time, yet now missing:
- quality_label

  warnings.warn(message, FutureWarning)


AttributeError: 'DecisionTreeClassifier' object has no attribute 'tree_'

In [80]:
print("Confusion matrix:")
print(confusion_matrix(y_test, clf))

Confusion matrix:
[[  7  25   7]
 [ 38 825 264]
 [  3 151 150]]


In [82]:
#Visualisation of the CM

%matplotlib inline

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(5,4))
sns.heatmap(confusion_matrix, annot=True)
plt.xlabel("Predicted")
plt.ylabel("Truth")


ValueError: Must pass 2-d input. shape=()

<Figure size 360x288 with 0 Axes>