In [47]:
# data normalisation with sklearn
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder

In [48]:
from sklearn.preprocessing import LabelEncoder

In [49]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats


In [50]:
white_wine = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv', sep=";")

In [51]:
ohe = OneHotEncoder

In [52]:
white_wine['quality_label'] = white_wine['quality'].apply(lambda value: 'low'
if value <= 4 else 'medium'
if value <= 6 else 'high')

# 3 4 5 are low, 6 7 medium, 8 and nonexistent 9 are high
#changed to: 3 4 low, 5 6 medium, 7 8 (and 9) high

white_wine['quality_label'] = pd.Categorical(white_wine['quality_label'],
categories=['low', 'medium', 'high'])

white_wine

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality quality_label  
0         8.8        6        medium  
1         9.5        6        medium  
2        10.1        6        medium  
3         9.9        6        medium  
4         9.9        6        medium  
...       ...      ...           ...  
4893     11.2        6        medium  
4894      9.6        5        medium  
4895      9.4        6        medium  
4896     12.8        7          high  
4897     11.8        6        medium  

[4898 rows x 13 columns]

In [53]:
#Skewness measures asymmetry in the data distribution

#print(white_wine['residual sugar'].astype(float).skew())

In [54]:
#Kurtosis identifies outliers: data with high kurtosis (heavy-tailed data) is proof of outliers, and data with low kurtosis (light-tailed data) lacks them.

#print(white_wine['residual sugar'].astype(float).kurt())

In [55]:
white_wine["quality"].unique()

array([6, 5, 7, 8, 4, 3, 9])

In [56]:
# x is all the features Im keeping
# y is target, quality , the new name.

#X.drop(['SalePrice'],axis=1,inplace=True) REMEMBER THE INPLACE!!

In [57]:
white_wine["quality_label"].unique()
white_wine ["quality_label"].value_counts()

medium    3655
high      1060
low        183
Name: quality_label, dtype: int64

In [58]:
le = LabelEncoder()

In [59]:
new_wine = pd.DataFrame(white_wine, columns=['quality_label'])

new_wine['quality_label'] = new_wine['quality_label'].astype('category')

new_wine['quality_label_Cat'] = new_wine['quality_label'].cat.codes

new_wine

quality_label  quality_label_Cat
0           medium                  1
1           medium                  1
2           medium                  1
3           medium                  1
4           medium                  1
...            ...                ...
4893        medium                  1
4894        medium                  1
4895        medium                  1
4896          high                  2
4897        medium                  1

[4898 rows x 2 columns]

In [60]:
new_wine.tail(20)

quality_label  quality_label_Cat
4878           low                  0
4879        medium                  1
4880        medium                  1
4881        medium                  1
4882        medium                  1
4883        medium                  1
4884        medium                  1
4885        medium                  1
4886          high                  2
4887          high                  2
4888        medium                  1
4889        medium                  1
4890        medium                  1
4891        medium                  1
4892        medium                  1
4893        medium                  1
4894        medium                  1
4895        medium                  1
4896          high                  2
4897        medium                  1

In [61]:
x_data = white_wine[["fixed acidity", "volatile acidity", "citric acid", "residual sugar", "chlorides", "free sulfur dioxide", "total sulfur dioxide", "density", "pH", "sulphates", "alcohol"]]
y_data = new_wine["quality_label_Cat"]


In [62]:
new_frame = [white_wine, new_wine]
new_frame


[      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
 0               7.0              0.27         0.36            20.7      0.045   
 1               6.3              0.30         0.34             1.6      0.049   
 2               8.1              0.28         0.40             6.9      0.050   
 3               7.2              0.23         0.32             8.5      0.058   
 4               7.2              0.23         0.32             8.5      0.058   
 ...             ...               ...          ...             ...        ...   
 4893            6.2              0.21         0.29             1.6      0.039   
 4894            6.6              0.32         0.36             8.0      0.047   
 4895            6.5              0.24         0.19             1.2      0.041   
 4896            5.5              0.29         0.30             1.1      0.022   
 4897            6.0              0.21         0.38             0.8      0.020   
 
       free su

In [63]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_data, y_data ,test_size = 0.3, shuffle=False)
x_train, x_test, y_train, y_test


(      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
 0               7.0              0.27         0.36           20.70      0.045   
 1               6.3              0.30         0.34            1.60      0.049   
 2               8.1              0.28         0.40            6.90      0.050   
 3               7.2              0.23         0.32            8.50      0.058   
 4               7.2              0.23         0.32            8.50      0.058   
 ...             ...               ...          ...             ...        ...   
 3423            7.1              0.18         0.39           14.50      0.051   
 3424            6.4              0.32         0.27            4.90      0.034   
 3425            7.1              0.17         0.40           14.55      0.047   
 3426            7.1              0.17         0.40           14.55      0.047   
 3427            5.8              0.24         0.26           10.05      0.039   
 
       free su

In [64]:
# data normalisation with sklearn
from sklearn.preprocessing import MinMaxScaler

# fit scaler on training data
norm = MinMaxScaler().fit(x_train)

# transform training data
X_train_norm = norm.transform(x_train)

# transform testing data
X_test_norm = norm.transform(x_test)

In [65]:
len(x_train)

3428

In [66]:
y_train

0       1
1       1
2       1
3       1
4       1
       ..
3423    1
3424    1
3425    1
3426    1
3427    1
Name: quality_label_Cat, Length: 3428, dtype: int8

In [67]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression

In [68]:

lr = LogisticRegression()
lr.fit(x_train, y_train)

/Users/monicavillarfuentes/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [73]:

pred_lr = lr.predict(x_test)
pred_lr

array([1, 1, 1, ..., 1, 2, 2], dtype=int8)

In [70]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler


In [71]:
confusion_matrix = (y_test, pred_lr)
confusion_matrix


(3428    1
 3429    1
 3430    1
 3431    1
 3432    1
        ..
 4893    1
 4894    1
 4895    1
 4896    2
 4897    1
 Name: quality_label_Cat, Length: 1470, dtype: int8,
 array([1, 1, 1, ..., 1, 2, 2], dtype=int8))

In [ ]:
#run the classification report and accuracy score

In [ ]:
print("Accuracy score:", accuracy_score(y_test, pred_lr))

Accuracy score: 0.7442176870748299


In [ ]:
from sklearn.metrics import cohen_kappa_score

In [ ]:
kappa = cohen_kappa_score (pred_lr, y_test)
kappa

0.30881229311701

In [ ]:
print(classification_report(y_test, pred_lr, target_names=["low","medium","high"]))

              precision    recall  f1-score   support

         low       0.00      0.00      0.00        39
      medium       0.84      0.83      0.83      1127
        high       0.45      0.53      0.48       304

    accuracy                           0.74      1470
   macro avg       0.43      0.45      0.44      1470
weighted avg       0.74      0.74      0.74      1470



/Users/monicavillarfuentes/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/monicavillarfuentes/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/monicavillarfuentes/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, m